// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuiQu7bfp2k1CB7pbXHJST_P2WDf_ftkU',
    appId: '1:851501712917:web:e84987c65ab15c6c7eb01c',
    messagingSenderId: '851501712917',
    projectId: 'androidproject-bafc7',
    authDomain: 'androidproject-bafc7.firebaseapp.com',
    storageBucket: 'androidproject-bafc7.appspot.com',
    measurementId: 'G-YE6L6GG19L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLvhGAxR5K_IgB_YBjtXkBjCBIC4pXK8',
    appId: '1:851501712917:android:1f347617a2aa87927eb01c',
    messagingSenderId: '851501712917',
    projectId: 'androidproject-bafc7',
    storageBucket: 'androidproject-bafc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmP8Z_Sre2vpZgrX_9U7Fg4YFC52PZgGI',
    appId: '1:851501712917:ios:f63415dd7a427c597eb01c',
    messagingSenderId: '851501712917',
    projectId: 'androidproject-bafc7',
    storageBucket: 'androidproject-bafc7.appspot.com',
    iosBundleId: 'com.example.aashiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmP8Z_Sre2vpZgrX_9U7Fg4YFC52PZgGI',
    appId: '1:851501712917:ios:4784b7f9cfa1faf57eb01c',
    messagingSenderId: '851501712917',
    projectId: 'androidproject-bafc7',
    storageBucket: 'androidproject-bafc7.appspot.com',
    iosBundleId: 'com.example.aashiProject.RunnerTests',
  );
}
